import { IsEnum, IsNotEmpty, IsString } from 'class-validator';

export class CreateAppraisalCycleDto {
  @IsString()
  @IsNotEmpty()
  name!: string;

  @IsString()
  @IsNotEmpty()
  startDate!: string;

  @IsString()
  @IsNotEmpty()
  endDate!: string;

  @IsEnum(['upcoming', 'active', 'closed'], {
    message: 'Status must be upcoming, active, or closed',
  })
  status!: 'upcoming' | 'active' | 'closed';

  isAutoGenerated?: boolean;
}
